version: '3.9'

services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/esearch
    ports:
      - 8000:8000
    env_file:
      - .env
  elasticsearch:
    image: elasticsearch:8.12.2
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    